packages:
  - packages/*
  - apps/*

catalogs:
  build:
    '@tailwindcss/vite': ^4.1.12
    '@tsconfig/node24': ^24.0.1
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    '@vue/tsconfig': ^0.8.1
    tsdown: ^0.14.2
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.4
    vite-plugin-dts: ^4.5.4
    vite-plugin-vue-devtools: ^8.0.1
    vue-tsc: ^3.0.6
  dev:
    jiti: ^2.5.1
    less: ^4.4.1
    lint-staged: ^16.1.6
    mockjs: ^1.1.0
    npm-run-all2: ^8.0.4
    picocolors: ^1.1.1
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.1.12
    taze: ^19.4.0
  eslint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
  frontend:
    '@xsin/vue-waterfall': workspace:*
    '@xsin/vue-waterfall-core': workspace:*
    vue: ^3.5.21
  release:
    '@semantic-release/changelog': ^6.0.3
    '@semantic-release/git': ^10.0.1
    bumpp: ^10.2.3
    semantic-release: ^24.2.7
  test:
    '@playwright/test': ^1.55.0
    '@testing-library/jest-dom': ^6.8.0',
    '@testing-library/user-event': ^14.6.1,
    '@testing-library/vue': ^8.1.0,
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': 3.2.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    jsdom: ^26.1.0
    playwright: ^1.55.0
    vitest: ^3.2.4
  types:
    '@types/mockjs': ^1.0.10
    '@types/node': ^24.3.0
    '@types/resize-observer-browser': ^0.1.11

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - simple-git-hooks
